name = "SubstratumNode"
identifier = "net.substratum.node"
icon = ["substratum.png"]
version = "1.0.0"
copyright = "Copyright (c) Substratum Services 2017. All rights reserved."
short_description = "SubstratumNode for the decentralized web"
long_description = """
SubstratumNode allows members to make money while they sleep.
"""
